name: AzureContainerRegistryExtensions-v0.$(date:yy)$(DayOfYear).$(rev:r)-$(Build.SourceBranchName)
trigger:
- master
- Issue*

pr:
- master

pool:
  name: MacNetCorePools
  demands: npm
workspace:
 clean: true

steps:
- task: VersionExtractor@4
  name: versionExtractor
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(Build.BuildNumber)'

- task: TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: Npm@1
  displayName: TypeScript Install
  inputs:
    command: 'custom'
    workingDir: 'ACRAKSAccess'
    customCommand: 'install -g typescript' 

- task: Npm@1
  displayName: 'npm install ACRAKSAccess'
  inputs:
    workingDir: ACRAKSAccess
    customCommand: 'run publishExt'
    verbose: false

- task: Npm@1
  displayName: 'Build ACRCredentials'
  inputs:
    workingDir: ACRCredentials
    customCommand: 'run publishExt'
    verbose: false

- task: PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    extensionVersion: '$(versionExtractor.fullVersion)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'